### ISSUE TITLE
problem trying to depoly site

### ISSUE THREAD

**Issue by frako23** [hellotham/hello-astro#31]
Hi! 

i've tried to deploy your site on github pages, vercel and netlify and it has been impossible

when trying `pnpm preview `my terminal shows this error

`$ pnpm preview

> hello-astro@3.2.6 preview C:\Users\USUARIO\Desktop\Programación\Proyectos\hello-astro
> astro preview
[preview] The @astrojs/vercel/serverless adapter does not support the preview command.
  Stack trace:
    at preview (file:///C:/Users/USUARIO/Desktop/Programaci%C3%B3n/Proyectos/hello-astro/node_modules/.pnpm/astro@4.0.7_typescript@5.3.3/node_modules/astro/dist/core/preview/index.js:31:11)
    at async runCommand (file:///C:/Users/USUARIO/Desktop/Programaci%C3%B3n/Proyectos/hello-astro/node_modules/.pnpm/astro@4.0.7_typescript@5.3.3/node_modules/astro/dist/cli/index.js:129:22)
 ELIFECYCLE  Command failed with exit code 1.`

**Comment by ChristineTham** [comment]
Hi are you still experiencing this problem?

I am not able to replicate your issue (I am using a Mac and node 20):

```
$ pnpm preview

> hello-astro@3.2.6 preview /Volumes/Data/github/hello-astro
> astro preview


 astro  v4.0.7 ready in 5 ms

┃ Local    http://localhost:4321/hello-astro/
┃ Network  use --host to expose
```
